FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
ENV APPLICATIONINSIGHTS_CONNECTION_STRING="***your-application-insights-connection-string***"
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "QuickStart3_0.dll"]